### ISSUE TITLE
restore model fail

### ISSUE THREAD

**Issue by didadida-r** [modelscope/ClearerVoice-Studio#5]
Hi, the training is fail during the restoring process.

```
Train Epoch: 11/100 Step: 940/965 | 0.770s/batch | lr 5.0000e-04 || Mask_Loss 1.4892
Train Epoch: 11/100 Step: 950/965 | 0.769s/batch | lr 5.0000e-04 || Mask_Loss 1.7748
Train Epoch: 11/100 Step: 960/965 | 0.769s/batch | lr 5.0000e-04 || Mask_Loss 1.6740
Train Summary | End of Epoch 11 | Time 742.134s | Train Loss 1.6343
Valid Summary | End of Epoch 11 | Time 25.712s | Valid Loss 1.4752
Loading checkpoint: /home/test/exp_dir/denoiser/clear_voice-data_demand/checkpoints/MossFormer2_SE_48K/last_best_checkpoint
=> Reloaded previous model and optimizer. Continue training ...
reload from last best checkpoint
Traceback (most recent call last):
  File "/home/test/code/enhance/enhance_clearvoice/train/speech_enhancement/train.py", line 139, in <module>
    main(args)
  File "/home/test/code/enhance/enhance_clearvoice/train/speech_enhancement/train.py", line 79, in main
    solver.train()
  File "/home/test/code/enhance/enhance_clearvoice/train/speech_enhancement/solver.py", line 236, in train
    if self.print: print('Learning rate adjusted to: {lr:.6f}'.format(self.optimizer.param_groups[0]["lr"]))
KeyError: 'lr'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 6241) of binary: /home/test/python_env/anaconda3/envs/enh_clearvoice/bin/python
Traceback (most recent call last):
  File "/home/test/python_env/anaconda3/envs/enh_clearvoice/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/test/python_env/anaconda3/envs/enh_clearvoice/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/test/python_env/anaconda3/envs/enh_clearvoice/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/test/python_env/anaconda3/envs/enh_clearvoice/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/test/python_env/anaconda3/envs/enh_clearvoice/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/test/python_env/anaconda3/envs/enh_clearvoice/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/test/python_env/anaconda3/envs/enh_clearvoice/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/test/python_env/anaconda3/envs/enh_clearvoice/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError
```

**Comment by alibabasglab** [comment]
Thank you for your feedback, we are looking into this case

**Comment by alibabasglab** [comment]
Hi, we have fixed the issue. Please pull the repo and try again. Thanks.

**Comment by didadida-r** [comment]
it's okay, thanks
